version: '3'
services:
  app:
    build: .
    working_dir: '/app'
    tty: true
    volumes:
      - .:/app
      - virtualenvs:/root/.cache/pypoetry/virtualenvs
  
volumes:
  virtualenvs:
    driver: local
